version: "3"

services:
  web:
    image: radio1_web:stack
    command: ["npm", "start"]
    environment:
      - MONGOHOST=radio1_db
    depends_on:
      - db
    ports:
      - "80:3000"
    networks:
      - radio1net
  db:
    image: mongo
    volumes:
      - /home/ec2-user/db/data:/data/db
    networks:
      - radio1net

  scraper:
    image: radio1_scraper:stack
    command: ["python", "r1.py"]
    environment:
      - MONGOHOST=radio1_db
    depends_on:
      - db
    networks:
      - radio1net
    deploy:
      restart_policy:
        condition: any
        delay: 15m
        window: 5s

  mongo-admin:
    image: adicom/admin-mongo
    ports:
      - "1234:1234"
    networks:
      - radio1net
    environment:
      - HOST=radio1_db
      - PORT=1234
      - PASSWORD=radio1
    depends_on:
      - db

networks:
  radio1net:

